name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Build Lambda package
        run: |
          docker run --rm -v ${{ github.workspace }}:/var/task "lambci/lambda:build-python3.8" /bin/sh -c "cd src && pip install -r requirements.txt -t . && zip -r ../lambda_package.zip ."
        working-directory: src

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Set Variables
        run: |
          echo "export TF_CLOUD_ORGANIZATION=honeybee-logic" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform -chdir=terraform init -backend-config="bucket=hbl.tfstate"
      - name: Plan Terraform
        run: terraform -chdir=terraform plan
      - name: Apply Terraform
        run: terraform -chdir=terraform apply -auto-approve
